### ISSUE TITLE
Missing value sampling does not work with multivariate distributions

### ISSUE THREAD

**Issue by bgroenks96** [TuringLang/Turing.jl#1653] opened 2021-06-27 21:40 UTC
It appears that vector and/or matrix valued observations with missing values mixed in do not work with multivariate likelihoods. Simple MWE:

```julia
using Turing

@model function mvlinreg(X,Y)
    N, k = size(X)
    σ ~ InverseGamma(2,3)
    β ~ MvNormal(zeros(k,),1.0)
    α ~ Normal(0,1.0)
    μ = X*β .+ α
    Y ~ MvNormal(μ, σ)
end

X = randn(10,5)
Y = Vector{Union{Missing,Float64}}(undef,10)
Y .= randn(10)
Y[2] = missing
model = mvlinreg(X,Y)
chain = sample(model, NUTS(), 500)
```
Fails with error:

```
ERROR: LoadError: MethodError: no method matching loglikelihood(::IsoNormal, ::Vector{Union{Missing, Float64}})
```
One might hope that, for isotropic cases, `arraydist` would be a possible workaround. Sadly, this is not the case.

```julia
@model function mvlinreg2(X,Y)
    N, k = size(X)
    σ ~ InverseGamma(2,3)
    β ~ MvNormal(zeros(k,),1.0)
    α ~ Normal(0,1.0)
    μ = X*β .+ α
    Y ~ arraydist(Normal.(μ,σ))
end

model = mvlinreg2(X,randn(10))
chain = sample(model, NUTS(), 500)
```
Fails with:

```
ERROR: LoadError: MethodError: no method matching loglikelihood(::Product{Continuous, Normal{Float64}, Vector{Normal{Float64}}}, ::Vector{Union{Missing, Float64}})
```

Given that missing values are a very common problem, and that other MCMC tools like pymc3 and stan can handle this case with no issues, it would be nice to get this fixed as soon as possible. At the moment, I have to resort to using nested loops whenever missing values are present which really kills performance.

On the face of it, it looks like just a missing dispatch, but I haven't dug into the code enough yet to see if there are some deeper challenges here.

**Comment by bgroenks96** [comment] 2021-06-27 21:52
Ah, possibly related (or even a duplicate of?) #1559

**Comment by devmotion** [comment] 2021-06-27 22:11
Yes, this seems to be a duplicate of https://github.com/TuringLang/Turing.jl/issues/1559.

**Closed by devmotion** 2021-06-27 22:11 UTC

**Comment by bgroenks96** [comment] 2021-06-27 22:20
@devmotion Do bear in mind that the use-case is different here from #1559 and the proposed workaround in that discussion is of course not suitable here.

**Comment by devmotion** [comment] 2021-06-27 22:52
Yes, I am aware of this, however, it seems to be the same problems fundamentally: Distributions does not define `loglikelihood` for partially missing data, in general filling the missing data correctly is non-trivial, and even more fundamentally for loops and vectorized distributions are not equivalent in Turing.

**Comment by jgslazzaro** [comment] 2022-06-13 11:43
I am facing the same issue. 

```julia
y  ~ MvNormal(zeros(50), 0.1) 
```
But `y` has some `missing` entries. 
Does anyone found a workaround? 
I am currently looping over univariate Normals but is this the best option?

**Comment by bgroenks96** [comment] 2022-06-13 11:48
Your two options are to either loop over univariate Normals or to set up a missing data model which explicitly separates the missing and non-missing values. Here is a simple example for regression tasks which treats the missing values as sampled independently from the likelihood:
```julia
function regression(modelfunc, X, Y=missing, args...; kwargs...)
    if ismissing(Y)
        return modelfunc(X, 1:length(X), args...; kwargs...)
    else
        i_miss = findall(ismissing, Y)
        i_data = [i for i in 1:size(X,1) if i ∉ i_miss]
        Y = collect(skipmissing(Y))
        m = modelfunc(X, i_data, args...; kwargs...)
        return Turing.condition(m, Y=Y)
    end
end

```
