### ISSUE TITLE
Missing Pkg in dependencies

### ISSUE THREAD

**Issue by dfioravanti** [TuringLang/Turing.jl#1020] opened 2019-12-11 08:56 UTC
Hi everyone, I just updated Turing to 0.7.4 and while recompiling after importing the package I just got this warning.

```
┌ Warning: Package Turing does not have Pkg in its dependencies:
│ - If you have Turing checked out for development and have
│   added Pkg as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Turing
│ Loading Pkg into Turing from project dependency, future warnings for Turing are suppressed.
└ @ nothing nothing:904
```

thanks a lot for the amazing work

**Comment by mohamed82008** [comment] 2019-12-11 09:42
I cannot reproduce this. Which Julia version are you using? Did you try calling `] resolve`?

**Comment by dfioravanti** [comment] 2019-12-11 09:56
I am running julia 1.3 on ubuntu with the "Generic Linux Binaries for x86". I tried calling `] resolve` but nothing happens. 

Now the warning is gone, I deleted Turing, deleted the cache, exited Julia, reinstalled Truing and reimported but it does not show up. No idea, maybe it was just a random effect of updating the packages and not restarting Julia.

**Comment by mohamed82008** [comment] 2019-12-11 09:59
Could be a cache update thing in Pkg. I will close this for now. Please report again if it shows up.

**Closed by mohamed82008** 2019-12-11 09:59 UTC
