### ISSUE TITLE
ERROR: LoadError: `getϵ(adaptor::AdvancedHMC.Adaptation.NoAdaptation)` is not implemented.

### ISSUE THREAD

**Issue by gino244** [TuringLang/Turing.jl#1071] opened 2020-01-14 08:39 UTC
I have run the code bellow, then error in the sample function as the title with Turing 0.8.1 and Julia 1.3.1. I am not sure the error results from calling AdvancedHMC from Turing or from AdvancedHMC itself.

I haven't seen this error in Turing 0.7.4.

`
using Turing

function test()
    ## create data
    x = hcat(collect(1:100), ones(Int, 100))
    a, b, s = 8, 5, 2
    y = x * [a, b] + rand(100) * s

    ## model
    @model m(X, Y) = begin
        a ~ Normal(0, 10)
        b ~ Normal(0, 10)
        s ~ truncated(Normal(0, 10), 0, 10)
    end

    ## sampling
    chn = sample(m(x, y), NUTS(0.65), 1000)

    ## describe
    describe(chn)
end

test()
`

**Running log with ERROR:**
> ┌ Info: Found initial step size
└   ϵ = 6.4
ERROR: LoadError: `getϵ(adaptor::AdvancedHMC.Adaptation.NoAdaptation)` is not implemented.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] getϵ(::AdvancedHMC.Adaptation.NoAdaptation) at /home/ogino/.julia/packages/AdvancedHMC/NYFTw/src/adaptation/Adaptation.jl:19
 [3] #step!#32(::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:iteration,),Tuple{Int64}}}, ::typeof(AbstractMCMC.step!), ::Random._GLOBAL_RNG, ::DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:X, :Y),Tuple{Array{Int64,2},Array{Float64,1}}},DynamicPPL.ModelGen{(:X, :Y),var"##m#453#4"{var"##m#453#3#5"},NamedTuple{(),Tuple{}}},Val{()}}, ::DynamicPPL.Sampler{NUTS{Turing.Core.ForwardDiffAD{40},(),AdvancedHMC.Adaptation.DiagEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:a, :b, :s),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:a},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:a},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:b},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:b},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:s},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{DynamicPPL.VarName{:s},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.NUTS{AdvancedHMC.MultinomialTS,AdvancedHMC.GeneralisedNoUTurn,AdvancedHMC.Leapfrog{Float64},Float64},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}, ::Int64) at /home/ogino/.julia/packages/Turing/a0nSz/src/inference/hmc.jl:331
 [4] (::AbstractMCMC.var"#kw##step!")(::NamedTuple{(:iteration,),Tuple{Int64}}, ::typeof(AbstractMCMC.step!), ::Random._GLOBAL_RNG, ::DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:X, :Y),Tuple{Array{Int64,2},Array{Float64,1}}},DynamicPPL.ModelGen{(:X, :Y),var"##m#453#4"{var"##m#453#3#5"},NamedTuple{(),Tuple{}}},Val{()}}, ::DynamicPPL.Sampler{NUTS{Turing.Core.ForwardDiffAD{40},(),AdvancedHMC.Adaptation.DiagEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:a, :b, :s),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:a},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:a},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:b},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:b},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:s},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{DynamicPPL.VarName{:s},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.NUTS{AdvancedHMC.MultinomialTS,AdvancedHMC.GeneralisedNoUTurn,AdvancedHMC.Leapfrog{Float64},Float64},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}, ::Int64) at ./none:0
 [5] #sample#6(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(sample), ::Random._GLOBAL_RNG, ::DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:X, :Y),Tuple{Array{Int64,2},Array{Float64,1}}},DynamicPPL.ModelGen{(:X, :Y),var"##m#453#4"{var"##m#453#3#5"},NamedTuple{(),Tuple{}}},Val{()}}, ::DynamicPPL.Sampler{NUTS{Turing.Core.ForwardDiffAD{40},(),AdvancedHMC.Adaptation.DiagEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:a, :b, :s),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:a},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:a},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:b},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:b},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:s},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{DynamicPPL.VarName{:s},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.NUTS{AdvancedHMC.MultinomialTS,AdvancedHMC.GeneralisedNoUTurn,AdvancedHMC.Leapfrog{Float64},Float64},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}, ::Int64) at /home/ogino/.julia/packages/AbstractMCMC/pi3j6/src/AbstractMCMC.jl:217
 [6] #sample at ./none:0 [inlined]
 [7] #sample#5 at /home/ogino/.julia/packages/AbstractMCMC/pi3j6/src/AbstractMCMC.jl:194 [inlined]
 [8] (::StatsBase.var"#kw##sample")(::NamedTuple{(:progress,),Tuple{Bool}}, ::typeof(sample), ::DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:X, :Y),Tuple{Array{Int64,2},Array{Float64,1}}},DynamicPPL.ModelGen{(:X, :Y),var"##m#453#4"{var"##m#453#3#5"},NamedTuple{(),Tuple{}}},Val{()}}, ::DynamicPPL.Sampler{NUTS{Turing.Core.ForwardDiffAD{40},(),AdvancedHMC.Adaptation.DiagEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:a, :b, :s),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:a},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:a},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:b},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:b},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:s},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{DynamicPPL.VarName{:s},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.NUTS{AdvancedHMC.MultinomialTS,AdvancedHMC.GeneralisedNoUTurn,AdvancedHMC.Leapfrog{Float64},Float64},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}, ::Int64) at ./none:0
 [9] #sample#2(::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(sample), ::DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:X, :Y),Tuple{Array{Int64,2},Array{Float64,1}}},DynamicPPL.ModelGen{(:X, :Y),var"##m#453#4"{var"##m#453#3#5"},NamedTuple{(),Tuple{}}},Val{()}}, ::NUTS{Turing.Core.ForwardDiffAD{40},(),AdvancedHMC.Adaptation.DiagEuclideanMetric}, ::Int64) at /home/ogino/.julia/packages/Turing/a0nSz/src/inference/Inference.jl:159
 [10] sample(::DynamicPPL.Model{var"##inner_function#433#6",NamedTuple{(:X, :Y),Tuple{Array{Int64,2},Array{Float64,1}}},DynamicPPL.ModelGen{(:X, :Y),var"##m#453#4"{var"##m#453#3#5"},NamedTuple{(),Tuple{}}},Val{()}}, ::NUTS{Turing.Core.ForwardDiffAD{40},(),AdvancedHMC.Adaptation.DiagEuclideanMetric}, ::Int64) at /home/ogino/.julia/packages/Turing/a0nSz/src/inference/Inference.jl:158
 [11] test() at /home/ogino/test.jl:17
 [12] top-level scope at /home/ogino/test.jl:23
 [13] include at ./boot.jl:328 [inlined]
 [14] include_relative(::Module, ::String) at ./loading.jl:1105
 [15] include(::Module, ::String) at ./Base.jl:31
 [16] exec_options(::Base.JLOptions) at ./client.jl:287
 [17] _start() at ./client.jl:460
in expression starting at /home/ogino/test.jl:23

**Comment by yebai** [comment] 2020-01-17 17:25
@xukai92 can you take a look at this? Might be caused by recent changes in AHMC.

**Comment by xukai92** [comment] 2020-01-17 17:51
I believe @cpfiffer has fixed this in #1063

**Comment by cpfiffer** [comment] 2020-01-19 00:37
This should be fixed by releasing a new version: 

@JuliaRegistrator register

**Comment by cpfiffer** [comment] 2020-01-19 01:22
@gino244 try updating Turing to 0.8.3 using `]up Turing`. This should fix your issue. Feel free to open this back up if updating does not fix your issue.

**Closed by cpfiffer** 2020-01-19 01:22 UTC

**Comment by gino244** [comment] 2020-01-19 22:45
@cpfiffer thanks for fixing the issue. It is fixed with Turing 0.8.3. Thanks!
