### ISSUE TITLE
Taking multi-threaded random number generation a bit more seriously

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Turing.jl#1260] opened 2020-05-04 22:39 UTC
Currently, a thread-local random number generator is used in certain places even when a random number generator is passed by the user to `sample`. This should be fixed by passing the input `rng` through to any function that might call `rand`.

**Comment by devmotion** [comment] 2020-05-05 07:19
As on Slack, I want to note that this problem is not specific to multithreading but exists for singlethreading as well. The AbstractMCMC interface correctly provides Turing (and any other downstream package) with (deep copies of) reproducible random number generators. However, since not all sampling steps and model evaluations use the provided RNG any sampling with non-standard RNGs in singlethreading and any RNG in multithreading will be non reproducible.

**Comment by cpfiffer** [comment] 2020-05-05 13:10
I think this is a problem endemic almost everywhere. I'm guilty of this almost everywhere in AdvancedMH, too.

**Comment by devmotion** [comment] 2020-05-20 15:31
Not fixed in Turing yet.

**Comment by xukai92** [comment] 2020-05-22 10:23
> The AbstractMCMC interface correctly provides Turing (and any other downstream package) with (deep copies of) reproducible random number generators. However, since not all sampling steps and model evaluations use the provided RNG any sampling with non-standard RNGs in singlethreading and any RNG in multithreading will be non reproducible.

I guess for HMC type alg. the only randomness on Turing side is initialisation. As long as RNGs are passed to AHMC correctly, it should be reproducibile - there are reproducibility test on the AHMC side.

For SMC type alg., we need seperate reproducibility test on model evaluation in DynamicPPL, and reproducibility test for e.g. AdvancedSMC module.

We can then look what's missing if things still can't be reproduced.

**Comment by devmotion** [comment] 2020-05-22 14:52
The fixes for Turing are in https://github.com/devmotion/Turing.jl/tree/rng (was linked in the DynamicPPL PR), but they require a new DynamicPPL release. I added tests for HMC, MH, IS, PG, and ESS that all pass.

**Closed** 2020-05-23 14:28 UTC
