### ISSUE TITLE
Move SGLD and SGHMC to AdvancedHMC.jl

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#769] opened 2019-04-27 00:25 UTC

**Comment by xukai92** [comment] 2019-04-27 00:26
https://github.com/TuringLang/AdvancedHMC.jl/issues/60

**Comment by yebai** [comment] 2019-05-03 15:20
Duplicate of https://github.com/TuringLang/AdvancedHMC.jl/issues/60

**Closed by yebai** 2019-05-03 15:20 UTC
