### ISSUE TITLE
Add additional keyword arguments to the sample function

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#482] opened 2018-08-31 18:19 UTC
Currently, the sample function does not provide additional keyword arguments such as the number if burnin (warmup) iterations, thinning or random seed. I think it would be good to allow the user to specify these parameters either using additional keyword arguments of the sample function or by instantiating the sampler with these parameters. As these are all rather generic parameters, I would favour using the sample function as an entry point.

Example use:
```julia
@model gdemo(x) = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0,sqrt(s))
  x[1] ~ Normal(m, sqrt(s))
  x[2] ~ Normal(m, sqrt(s))
  return s, m
end

sample(gdemo([1.5, 2]), PG(10,1000); burnin = 1000, thin = 2, seed = 145)
```

**Comment by trappmartin** [comment] 2018-09-03 13:50
See issue #448.

**Comment by yebai** [comment] 2019-05-13 11:07
Duplicate of https://github.com/TuringLang/Turing.jl/issues/746

**Closed by yebai** 2019-05-13 11:07 UTC
Labels: new-feature
