### ISSUE TITLE
Variational Bayes inference?

### ISSUE THREAD

**Issue by skanskan** [TuringLang/Turing.jl#606] opened 2018-11-23 14:00 UTC
Hello.

Can Turing.jl be use to do Variational Bayes inference? 
it’s “universal”, though maybe only useful for MCMC. I can’t find it on its documentation.
Will this option be added?

**Comment by xukai92** [comment] 2018-11-23 14:13
VI is not-supported at the moment. But this is something we will look at in the future.

**Comment by outlace** [comment] 2019-01-09 00:21
I think this is a really important feature. Turing can't compete in the bayesian deep learning space against Pyro and TensorFlow Probability/Edward2 without variational methods. MCMC is utterly too slow in those settings.

**Comment by mohamed82008** [comment] 2019-01-09 00:54
@outlace No one denies VI's importance :) This is an open source project, so if you find this feature useful, you can start thinking about how to implement it and ask questions on the the Julia slack (https://julialang.slack.com), the #turing channel.

**Comment by outlace** [comment] 2019-01-09 01:43
@mohamed82008 Sorry, I see my previous comment was a little over-the-top. Thanks for the polite response. Yes, I am thinking about implementation of VI.  I think much can be improved over Pyro for example.

**Comment by yebai** [comment] 2019-05-07 08:46
Duplicate of #775

**Closed by yebai** 2019-05-07 08:46 UTC
