### ISSUE TITLE
Improve code for initialising `Sampler`

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#768] opened 2019-04-27 00:25 UTC
Codes are quite inconsistent, including
- check `space`
  - sometimes we pass `model` for this purpose
- we could simplify a lot of overloading by `s::Selector=Selector()`

**Comment by mohamed82008** [comment] 2019-04-28 00:28
See the `Turing.Inference.init_spl` function in [#660](https://github.com/TuringLang/Turing.jl/tree/mt/type_stability2/) which is relevant.

**Comment by yebai** [comment] 2019-05-03 15:21
Duplicate of https://github.com/TuringLang/Turing.jl/issues/746

**Closed by yebai** 2019-05-03 15:21 UTC
