### ISSUE TITLE
Truncated distributions with random bounds

### ISSUE THREAD

**Issue by arzwa** [TuringLang/Turing.jl#880] opened 2019-08-06 14:06 UTC
Hi, 

This is perhaps more an issue with Distributions.jl, but when one uses a `Truncated` distribution  with one of the bounds itself a random variable in a Turing model, a `StackOverFlowError` occurs in the distribution constructor when using a sampler that uses AD.  Here is a MWE: 

```julia
using Turing
using Distributions

@model trunctest(x) = begin
    bound ~ Uniform(0., 10.)
    for i in eachindex(x)
        x[i] ~ Truncated(Normal(0., 1.), -bound, bound)
    end
end

chain = sample(trunctest(randn(10)), HMC(1000, 0.1, 10))
```
which results in 

```
ERROR: StackOverflowError:
Stacktrace:
 [1] Type at /home/arzwa/.julia/packages/ForwardDiff/N0wMF/src/dual.jl:19 [inlined]
 [2] Type at /home/arzwa/.julia/packages/ForwardDiff/N0wMF/src/dual.jl:55 [inlined]
 [3] Type at /home/arzwa/.julia/packages/ForwardDiff/N0wMF/src/dual.jl:62 [inlined]
 [4] Type at /home/arzwa/.julia/packages/ForwardDiff/N0wMF/src/dual.jl:68 [inlined]
 [5] Type at /home/arzwa/.julia/packages/Tracker/RRYy6/src/lib/real.jl:108 [inlined]
 [6] Truncated(::Normal{Float64}, ::ForwardDiff.Dual{Nothing,Float64,1}, ::ForwardDiff.Dual{Nothing,Float64,1}) at /home/arzwa/.julia/packages/Distributions/tfkz4/src/truncate.jl:32 (repeats 80000 times)
```
The model above works fine with a Metropolis Hastings sampler (`chain = sample(trunctest(randn(10)), MH(1000, 0.1))`).

**Comment by trappmartin** [comment] 2019-08-28 10:03
This is currently not possible due to the strict typing in `Distributions.jl` and the way `AD` works. It would be great if you could open an issue or PR on `Distributions.jl`.

**Comment by xukai92** [comment] 2019-09-16 00:02
I can confirm this happens to `TruncatedNormal`. Really an AD issue.

**Comment by mohamed82008** [comment] 2019-09-26 03:56
https://github.com/JuliaStats/Distributions.jl/issues/745

**Comment by yebai** [comment] 2021-01-28 17:27
Closing since we don't intend to support this feature for now. Happy to revisit if there is a strong case in the future.

**Closed by yebai** 2021-01-28 17:27 UTC
Labels: wontfix
