### ISSUE TITLE
Multivariate normal issues

### ISSUE THREAD

**Issue by drmarios** [TuringLang/Turing.jl#1295] opened 2020-05-26 14:23 UTC
I tried to convert the mixture tutorial from univariate to bivariate mixtures: https://turing.ml/dev/tutorials/6-infinitemixturemodel/

Here's the new model:
```
@model infiniteGMM(x) = begin 
    
    # Hyper-parameters, i.e. concentration parameter and parameters of H.
    α = 1.0
    μ0 = [0.0, 0.0]
    σ0 = 1.0
    
    # Define random measure, e.g. Dirichlet process.
    rpm = DirichletProcess(α)
    
    # Define the base distribution, i.e. expected value of the Dirichlet process.
    H = MvNormal(μ0, σ0)
    
    # Latent assignment.
    z = tzeros(Int, length(x))
        
    # Locations of the infinitely many clusters.
    μ = TArray{TArray{Float64, 1}, 1}(undef, 0);

    for i in 1:length(x)
        
        # Number of clusters.
        K = maximum(z)
        nk = Vector{Int}(map(k -> sum(z .== k), 1:K))

        # Draw the latent assignment.
        z[i] ~ ChineseRestaurantProcess(rpm, nk)
        
        # Create a new cluster?
        if z[i] > K
            push!(μ, tzeros(2))
            # Draw location of new cluster.
            μ[z[i]] ~ H
        end
                
        # Draw observation.
        x[i] ~ MvNormal(μ[z[i]], 1.0)
    end
end
```

If I try to sample from it:
```
model = infiniteGMM(x);
chains = sample(model, MH(), 10);
```

I get the following error: 
```
MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type TArray{Float64,1}
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:AbstractArray at abstractarray.jl:14
  convert(::Type{T}, !Matched::Factorization) where T<:AbstractArray at 
```

Any ideas where this is coming from? Looks like again some dimensional/indexing mismatch.
I’m using a sample bivariate mixture as follows:
```
y1 = rand(MvNormal([1., 3.], 0.5), 250);
y2 = rand(MvNormal([-1., 0.], 0.5), 400);
x = reduce(hcat, [y1, y2])
```

My setup is Distributions v0.23.2 and Turing v0.13.0

**Comment by devmotion** [comment] 2020-05-26 14:56
The first problem I see (without closer inspection) is that you use `tzeros` and `TArray` with `MH` but actually these array types require particle samplers such as `SMC` or `PG` (as in the tutorial).

**Comment by drmarios** [comment] 2020-05-26 15:43
You're right re MH(). However I tried: 
``` chains = sample(model, PG(10), 100); ```
and also 
```
chains = sample(model,  SMC(), 100);
```
but get exactly the same error about 'convert' as reported above. So I reckon it's some indexing issue and not the sampler.

Error: 
```
MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type TArray{Float64,1}
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:AbstractArray at abstractarray.jl:14
  convert(::Type{T}, !Matched::Factorization) where T<:AbstractArray at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\LinearAlgebra\src\factorization.jl:55
  convert(::Type{T}, !Matched::T) where T at essentials.jl:171
  ...

Stacktrace:
 [1] setindex!(::Array{TArray{Float64,1},1}, ::Array{Float64,1}, ::Int64) at .\array.jl:826
```

**Comment by KDr2** [comment] 2020-05-27 03:27
I think it's fixed by https://github.com/TuringLang/Libtask.jl/pull/70.

**Comment by drmarios** [comment] 2020-05-27 12:31
The original issue re: convert is fixed now with Libtask 0.4.1. However, now get the following error when sampling using either PG() or SMC(). 

'''MethodError: no method matching logpdf(::MvNormal{Float64,PDMats.ScalMat{Float64},TArray{Float64,1}}, ::Float64)
Closest candidates are:
  logpdf(!Matched::Chernoff, ::Real) at C:\Users\marios\.julia\packages\Distributions\dTXqn\src\univariate\continuous\chernoff.jl:169
  logpdf(!Matched::Flat, ::Real) at C:\Users\marios\.julia\packages\Turing\Bw6ZJ\src\stdlib\distributions.jl:13
  logpdf(!Matched::Arcsine{T}, ::Real) where T<:Real at C:\Users\marios\.julia\packages\Distributions\dTXqn\src\univariate\continuous\arcsine.jl:83
'''

So it's something to do with MvNormal() distribution.

**Comment by devmotion** [comment] 2020-05-27 12:49
I assume the problem is `x` (which is not shown in your examples). You iterate over all elements over `x` and hence if `x` is a vector or matrix the statements `x[i] ~ MvNormal(...)` in your model definition are incorrect since `x[i]` is just a scalar. As the error states, a sample from a multivariate normal distribution can't be a scalar. So you have to provide `x` as a vector of vectors. Alternatively, if `x` is a matrix you could write `x[:, i] ~ MvNormal(...)` and iterate over the columns of `x`. Would be interesting to see if the first version is significantly faster since it avoids the reallocations from indexing `x[:, i]` in every model execution.

**Comment by drmarios** [comment] 2020-05-27 13:48
Yes, you're right, the issue was x[i]. 
This change:
```
        # Draw observation.
        x[:,i] ~ MvNormal(μ[z[i]], 1.0)
```
fixes the problem.

**Comment by devmotion** [comment] 2020-05-27 13:58
Great that it works now!

**Closed by devmotion** 2020-05-27 13:58 UTC
