### ISSUE TITLE
Can not load Turing.jl, LoadError: UndefVarError: AbstractChains not defined

### ISSUE THREAD

**Issue by yangcht** [TuringLang/Turing.jl#1367] opened 2020-07-31 19:56 UTC
Hi, I just installed Turing on my Juia v1.4, however, I am unable to use it. I got the following compiling errors. Any idea? Thanks a lot in advance!

```
julia> Pkg.add("Turing")
  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
 [no changes]
   Updating `~/.julia/environments/v1.4/Manifest.toml`
 [no changes]

julia> using Turing
[ Info: Precompiling Turing [fce5fe82-541a-59a6-adf8-730c64b5f9a0]
WARNING: could not import MCMCChains.AbstractChains into Turing
ERROR: LoadError: LoadError: UndefVarError: AbstractChains not defined
Stacktrace:
 [1] include(::Module, ::String) at ./Base.jl:377
 [2] include(::String) at /Users/yangcht/.julia/packages/Turing/eIa7P/src/Turing.jl:1
 [3] top-level scope at /Users/yangcht/.julia/packages/Turing/eIa7P/src/Turing.jl:119
 [4] include(::Module, ::String) at ./Base.jl:377
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:331 [inlined]
 [7] eval(::Expr) at ./client.jl:449
 [8] top-level scope at ./none:3
in expression starting at /Users/yangcht/.julia/packages/Turing/eIa7P/src/utilities/Utilities.jl:6
in expression starting at /Users/yangcht/.julia/packages/Turing/eIa7P/src/Turing.jl:119
ERROR: Failed to precompile Turing [fce5fe82-541a-59a6-adf8-730c64b5f9a0] to /Users/yangcht/.julia/compiled/v1.4/Turing/gm4QC_uuhai.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1272
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
```

**Comment by devmotion** [comment] 2020-07-31 19:57
Can you try the solution in https://github.com/TuringLang/Turing.jl/issues/1366#issuecomment-666662887? I assume your version of Turing is outdated.

**Comment by yangcht** [comment] 2020-07-31 20:04
Thanks! Indeed, I tried to update, but Julia says it can not find the version, which is really weird.

```
(@v1.4) pkg> add Turing@0.13.0
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Compat [34da2185]:
 Compat [34da2185] log:
 ├─possible versions are: [1.0.0-1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0-1.5.1, 2.0.0, 2.1.0, 2.2.0, 3.0.0, 3.1.0, 3.2.0, 3.3.0-3.3.1, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.9.0-3.9.1, 3.10.0, 3.11.0, 3.12.0, 3.13.0] or uninstalled
 ├─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: [1.0.0-1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0-1.5.1, 2.0.0, 2.1.0, 2.2.0, 3.0.0, 3.1.0, 3.2.0, 3.3.0-3.3.1, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.9.0-3.9.1, 3.10.0, 3.11.0, 3.12.0, 3.13.0]
 │ └─DataFrames [a93c6f00] log:
 │   ├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.4] or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.4]
 │   └─restricted by compatibility requirements with RDatasets [ce6b1742] to versions: [0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.4]
 │     └─RDatasets [ce6b1742] log:
 │       ├─possible versions are: [0.5.0, 0.6.0-0.6.9] or uninstalled
 │       └─restricted to versions * by an explicit requirement, leaving only versions [0.5.0, 0.6.0-0.6.9]
 ├─restricted by compatibility requirements with Winston [bd07be1c] to versions: [1.0.0-1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0-1.5.1, 2.0.0, 2.1.0, 2.2.0]
 │ └─Winston [bd07be1c] log:
 │   ├─possible versions are: [0.14.0-0.14.1, 0.15.0] or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions [0.14.0-0.14.1, 0.15.0]
 └─restricted by compatibility requirements with DistributionsAD [ced4e74d] to versions: [3.6.0, 3.7.0, 3.8.0, 3.9.0-3.9.1, 3.10.0, 3.11.0, 3.12.0, 3.13.0] — no versions left
   └─DistributionsAD [ced4e74d] log:
     ├─possible versions are: [0.1.0-0.1.4, 0.2.0, 0.3.0-0.3.2, 0.4.0-0.4.10, 0.5.0-0.5.3, 0.6.0-0.6.2] or uninstalled
     └─restricted by compatibility requirements with Turing [fce5fe82] to versions: [0.4.8-0.4.10, 0.5.0-0.5.3]
       └─Turing [fce5fe82] log:
         ├─possible versions are: [0.5.0-0.5.1, 0.6.0-0.6.2, 0.6.4-0.6.9, 0.6.11-0.6.15, 0.6.17-0.6.19, 0.6.21-0.6.23, 0.7.0-0.7.4, 0.8.0-0.8.3, 0.9.0-0.9.2, 0.10.0-0.10.1, 0.11.0, 0.12.0, 0.13.0] or uninstalled
         └─restricted to versions 0.13.0 by an explicit requirement, leaving only versions 0.13.0
```

**Comment by devmotion** [comment] 2020-07-31 20:08
To me it seems the problem is that Winston does not support Compat >= 3.6 which is required by Turing (or rather its dependency DistributionsAD). DataFrames should be fine, it seems to support these more recent versions of Compat. So I assume if you remove Winston you should be able to install the most recent version of Turing.

**Comment by devmotion** [comment] 2020-07-31 20:09
Maybe you could avoid the conflicts by using a separate environment for your Turing-based projects (see https://julialang.github.io/Pkg.jl/v1/environments/).

**Comment by yangcht** [comment] 2020-07-31 20:28
Thanks! That solves my problem!

**Comment by devmotion** [comment] 2020-07-31 20:43
Great :+1: I'll close this issue then.

**Closed by devmotion** 2020-07-31 20:43 UTC
