### ISSUE TITLE
HMM tutiroal is broken

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#1236] opened 2020-04-24 21:28 UTC
There are errors in https://turing.ml/dev/tutorials/4-bayeshmm/

**Comment by cpfiffer** [comment] 2020-04-25 00:10
Same as https://github.com/TuringLang/Turing.jl/issues/1148. The code works fine if you copy it into your REPL, the problem is actually with Weave. 

As a side note, we're pretty much unable to rerender any of our tutorials with Weave (see https://github.com/JunoLab/Weave.jl/issues/290) so many of these fixes also require a complete overhaul of how the tutorials are written to markdown.

**Comment by xukai92** [comment] 2020-04-25 16:36
Can we use the build-in converter of Jupyter to convert notebooks to HTML files as a workaround?

**Comment by cpfiffer** [comment] 2020-04-25 18:20
Yeah, I spent some time writing a bash script to run everything through `nbconvert`, but I couldn't find a way to specify which Julia kernel to use. If there was a quick way to do that we could get it done quite quickly. Maybe I just missed the setting somewhere?

**Comment by cpfiffer** [comment] 2020-05-10 15:57
Fixed with https://github.com/TuringLang/TuringTutorials/pull/60.

**Closed by cpfiffer** 2020-05-10 15:57 UTC
