### ISSUE TITLE
Segmentation fault when running tests on Julia v1.6.0-rc1

### ISSUE THREAD

**Issue by lmshk** [TuringLang/Turing.jl#1554] opened 2021-03-08 17:55 UTC
On a fresh installation of Julia `v1.6.0-rc1` with Turing `v0.15.1`, running `pkg> test Turing` always causes segmentation faults on my machine (`x86_64 GNU/Linux 5.11.1-arch1-1`).

The tracebacks vary, but the segfaults always seem to happen during GC. I have attached a couple of specimens:
- [Turing1.txt](https://github.com/TuringLang/Turing.jl/files/6103179/Turing1.txt)
- [Turing2.txt](https://github.com/TuringLang/Turing.jl/files/6103181/Turing2.txt)
- [Turing3.txt](https://github.com/TuringLang/Turing.jl/files/6103183/Turing3.txt)

When playing around with various Turing tutorials this problem has not occured yet, so this is not currently blocking my work, but I am willing to investigate if somebody points me in the right direction. (I have never used Turing before.)

**Comment by devmotion** [comment] 2021-03-08 18:29
This is expected and caused by Libtask. Its binary dependency Libtask_jll is not compatible with Julia 1.6 yet - it has to be linked against libjulia but the version for Julia 1.6 is not available yet (since Julia 1.6 is not released). However, there exists already a PR that will fix this issue once the new version of libjulia is available: https://github.com/JuliaPackaging/Yggdrasil/pull/2176

Therefore there's nothing that can be done here and it will be fixed (more or less) automatically when Julia 1.6 is released. As long as you don't use Libtask-dependent features (i.e., if you do not use particle filters), Turing should work fine on Julia 1.6 already now (but due to the Libtask_jll incompatibility an older version will be installed by default IIRC).

**Closed by devmotion** 2021-03-08 18:29 UTC

**Comment by lmshk** [comment] 2021-03-09 12:23
Thanks for the quick and detailed reply!

> Turing should work fine on Julia 1.6 already now (but due to the Libtask_jll incompatibility an older version will be installed by default IIRC)

I am a little confused about this: Doing `pkg> add Turing` installed the (older) `v0.15.1`, which has the tests failing as described above. So it also has the Libtask_jll incompatibility, right?

(Do I understand correctly that this issue would also affect Turing on a Julia compiled from `master`?)

**Comment by lmshk** [comment] 2021-03-09 13:03
All clear, thank you.
