### ISSUE TITLE
ForwardDiff cannot determine ordering of Dual tags for Laplace distributions

### ISSUE THREAD

**Issue by ManojGopalkrishnan** [TuringLang/Turing.jl#1300] opened 2020-05-28 16:57 UTC
I asked about my problem here: https://discourse.julialang.org/t/forwarddiff-cannot-determine-ordering-of-dual-tags/40345 and was directed to open an issue at Turing.

Here’s my MWE
```julia
@model function mwe(::Type{T} = Vector{Float64}) where {T}

    lvar ~ Uniform(5.0,15.0)

    u ~ filldist(truncated(Laplace(55.0, lvar), 10, Inf),10) 

    return u

end

mwemodel = mwe()

chainmwe = sample(mwemodel, NUTS(.65),3)
```

The error is:

```julia
Cannot determine ordering of Dual tags ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:lvar, :u),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:lvar,Tuple{}},Int64},Array{Uniform{Float64},1},Array{DynamicPPL.VarName{:lvar,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:u,Tuple{}},Int64},Array{Product{Continuous,Truncated{Laplace{Float64},Continuous,Float64},FillArrays.Fill{Truncated{Laplace{Float64},Continuous,Float64},1,Tuple{Base.OneTo{Int64}}}},1},Array{DynamicPPL.VarName{:u,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"###evaluator#333",(:T,),Tuple{Type{Array{Float64,1}}},(),DynamicPPL.ModelGen{var"###generator#334",(:T,),(:T,),Tuple{Type{Array{Float64,1}}}}},DynamicPPL.Sampler{NUTS{Turing.Core.ForwardDiffAD{40},(),AdvancedHMC.DiagEuclideanMetric},Turing.Inference.SamplerState{DynamicPPL.VarInfo{NamedTuple{(:lvar, :u),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:lvar,Tuple{}},Int64},Array{Uniform{Float64},1},Array{DynamicPPL.VarName{:lvar,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:u,Tuple{}},Int64},Array{Product{Continuous,Truncated{Laplace{Float64},Continuous,Float64},FillArrays.Fill{Truncated{Laplace{Float64},Continuous,Float64},1,Tuple{Base.OneTo{Int64}}}},1},Array{DynamicPPL.VarName{:u,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}}}},Float64} and Nothing
...
```

and goes on for more characters than allowed in the body here. Not able to figure this out! Why isn’t this working?

**Comment by devmotion** [comment] 2020-05-28 18:05
You can avoid the issue by defining your model as
```julia
@model function mwe()
    lvar ~ Uniform(5.0,15.0)
    T = typeof(lvar)
    u ~ filldist(truncated(Laplace(55.0, lvar), T(10.0), T(Inf)), 10)
    return u
end
```
(Note that there is no reason to specify the input argument `::Type{T}` since you have access to the type of `lvar` inside the function definition, and you didn't actually use `T` in your original version.) The underlying problem is the comparison in https://github.com/JuliaStats/Distributions.jl/blob/feae3ba9ada360d2980c901e7c737ca02bda7a31/src/truncate.jl#L116. Truncated normal distributions are handled differently and don't end up there, but for Laplace distributions Distributions falls back to Truncated. The comparison in this line errors if `d.lower` and `d.upper` are regular numbers but `x` is a dual number (i.e., `lvar` in your case). So the issue should be fixed properly upstream in Distributions, but hopefully for the time being the fix is helpful.

**Comment by devmotion** [comment] 2020-05-28 18:11
I think the proper fix upstream is just adding
```julia
Base.eltype(::Type{Laplace{T}}) where {T} = T
```
Then https://github.com/JuliaStats/Distributions.jl/blob/feae3ba9ada360d2980c901e7c737ca02bda7a31/src/truncate.jl#L25 should guarantee that the lower and upper bound of the truncated distribution are also dual numbers (as in the manual fix mentioned above). I'll quickly check if my intuition is correct.

**Comment by devmotion** [comment] 2020-05-28 18:20
I can confirm that defining `eltype` of `Laplace` fixes the problem.

**Comment by ManojGopalkrishnan** [comment] 2020-05-30 10:08
Thanks for the replies! I could get around the problem by typecasting the limits to truncated as suggested.

**Closed** 2021-12-16 19:12 UTC
