### ISSUE TITLE
Improving the speed of single program run

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#294] opened 2017-06-24 06:25 UTC
After https://github.com/yebai/Turing.jl/issues/275 we can focus on improving the speed of single program run, I think there are several things to check on the Turing.jl side:

1. Do `@model` add statements which may slow down the program?
2. Do `@~` add statements which may slow down the program?
3. Is run-time `VarName` generator slow?
  - I would believe that your implementation of that will be faster than mine because you use `map` and stuff but mine uses `while` and stacks.
4. Distribution construction? (https://github.com/yebai/Turing.jl/issues/166)
5. Storing Distribution object? (https://github.com/yebai/Turing.jl/issues/191)

Any other?

**Comment by xukai92** [comment] 2017-07-07 11:36
Try https://github.com/denizyuret/AutoGrad.jl

**Comment by ChrisRackauckas** [comment] 2017-07-24 00:23
AutoGrad is likely going to have issues on v0.6 for quite some time. I would just wait for Cassette.jl if you need backprop

**Comment by xukai92** [comment] 2017-07-24 12:04
Yes and they are also not compatible with all the distributions in Distributions.jl package. We actually solved the points mentioned in this issue except the AD part, which shows worse performance than reverse-mode AD (like AutoGrad.jl) in high dimension.

Is Cassette.jl just the ReverseDiff.jl?

**Comment by ChrisRackauckas** [comment] 2017-07-24 15:59
Yes. ReverseDiff.jl is being deprecated for Cassette.jl. It's discussed here:

https://www.youtube.com/watch?v=SXJ0ZfawzxA

**Comment by yebai** [comment] 2019-05-13 11:03
Duplicate of https://github.com/TuringLang/Turing.jl/issues/620

**Closed by yebai** 2019-05-13 11:04 UTC
Labels: speed-up
