### ISSUE TITLE
The Infinite Mixture Models tutorial error

### ISSUE THREAD

**Issue by patwa67** [TuringLang/Turing.jl#1589] opened 2021-04-16 14:21 UTC
It is not possible to use:
```# Extract the number of clusters for each sample of the Markov chain.
k = map(t -> length(unique(chain[:z].value[t,:,:])), 1:iterations);
```
it throws the error:
```ERROR: ArgumentError: index z not found```

**Comment by devmotion** [comment] 2021-04-16 15:49
This example uses an old version of MCMCChains. With newer versions you have to use
```julia
zvars = namesingroup(chain, :z)
k = map(t -> length(unique(chain[t, zvars, :])), 1:iterations)
```
(or something similar based on [`namesingroup`](https://turinglang.github.io/MCMCChains.jl/dev/getting-started/#Groups-of-parameters), the code is untested). The issue will be fixed by the reorganization and updates in https://github.com/TuringLang/TuringTutorials/pull/113.

**Comment by patwa67** [comment] 2021-04-16 17:03
No it doesn't work. The following works, but it just produces a vector of ones:
```
k = map(t -> length(unique(get_params(chain[t,zvars,:]))), 1:iterations);
```

**Comment by devmotion** [comment] 2021-04-16 17:14
I assume the problem is that you use `get_params`: it returns a `NamedTuple` of parameters (see https://turinglang.github.io/MCMCChains.jl/dev/chains/#MCMCChains.get_params-Tuple{Chains}). I guess
```julia
k = map(t -> length(unique(Array(chain[t, zvars, :]))), 1:iterations)
```
is better (I assumed, apparently incorrectly since it failed (?), that `chain[t, zvars, :]` returns already an array).

**Comment by patwa67** [comment] 2021-04-16 18:46
That works better, but what is the logic behind this array construction?

**Comment by devmotion** [comment] 2021-04-16 19:22
`Array(chain)` returns an array of the values in the chain, where as default the different chains are appended (i.e., the output has `#iterations * #chains` rows and `#parameters` columns): https://turinglang.github.io/MCMCChains.jl/dev/getting-started/#Exporting-Chains

**Comment by patwa67** [comment] 2021-04-19 20:58
OK, fine. I have run this example with some different settings and samplers. One strange thing occurs when I change from the SMC() (which mixes badly) to the PG() sampler. When I use SMC() the output in ```zvars``` and consequently the ```k``` variable corresponds well with the output in the locations variable  ```muvars = namesingroup(chain, :μ)```, i.e. there is one location for each cluster. However, when the PG() sampler is used, this is no longer the case, i.e. there are more locations than clusters. However, the number of clusters seems to be correct.

**Closed** 2021-04-29 12:43 UTC
