### ISSUE TITLE
How to non-centered parameterization in Turing?

### ISSUE THREAD

**Issue by krishvishal** [TuringLang/Turing.jl#1372] opened 2020-08-10 21:30 UTC
k is a random variable `k ~ Normal(μ, σ)`, μ and σ have some other priors. I want to use a non-centered parameterization of the prior. I want to do something like this

```
k_ ~ Normal(0, 1)
k = k_ * σ + μ
```

Since the above doesn't use `~` Turing doesn't record `k`, it only records `k_`. Is there a way to do this in Turing?

**Comment by torfjelde** [comment] 2020-08-11 00:35
This is essentially a duplicate of #1335 so I'll close this in favor of that issue.

But essentially the best solution as of right now is to use the `generated_quantities` method outlined in that issue.

**Closed by torfjelde** 2020-08-11 00:35 UTC
