### ISSUE TITLE
compiling issue? why am I getting this error?

### ISSUE THREAD

**Issue by danielchen26** [TuringLang/Turing.jl#690] opened 2019-02-19 23:25 UTC
julia> using Turing
[ Info: Precompiling Turing [fce5fe82-541a-59a6-adf8-730c64b5f9a0]
ERROR: LoadError: could not open file /Users/chentianchi/.julia/packages/Libtask/PyjUd/deps/deps.jl
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1044
 [3] include at ./sysimg.jl:29 [inlined]
 [4] include(::String) at /Users/chentianchi/.julia/packages/Libtask/PyjUd/src/Libtask.jl:1
 [5] top-level scope at none:0
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1044
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:319 [inlined]
 [11] eval(::Expr) at ./client.jl:393
 [12] top-level scope at ./none:3
in expression starting at /Users/chentianchi/.julia/packages/Libtask/PyjUd/src/Libtask.jl:5
ERROR: LoadError: Failed to precompile Libtask [6f1fad26-d15e-5dc8-ae53-837a1d7b8c9f] to /Users/chentianchi/.julia/compiled/v1.0/Libtask/KIaXx.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1203
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1044
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:319 [inlined]
 [11] eval(::Expr) at ./client.jl:393
 [12] top-level scope at ./none:3
in expression starting at /Users/chentianchi/.julia/packages/Turing/XlLTY/src/Turing.jl:14
ERROR: Failed to precompile Turing [fce5fe82-541a-59a6-adf8-730c64b5f9a0] to /Users/chentianchi/.julia/compiled/v1.0/Turing/gm4QC.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1203
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853

**Comment by mohamed82008** [comment] 2019-02-19 23:29
Can you post which version of Turing, Libtask and Julia you are using? It may help to do `]up` followed by `]build Libtask`, then try `using Turing`.

**Comment by danielchen26** [comment] 2019-02-19 23:30
I am using julia 1.03. and I updated to the latest Turing.
Here is error when build Libtask:

(v1.0) pkg> build Libtask
Building Libtask → `~/.julia/packages/Libtask/PyjUd/deps/build.log`
┌ Error: Error building `Libtask`:
│ dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
│ Referenced from: /Users/chentianchi/anaconda3/lib/libssh2.1.dylib
│ Reason: image not found
│ fatal: not a git repository (or any of the parent directories): .git
│ ERROR: LoadError: failed process: Process(`git -C /Users/chentianchi/.julia/packages/Libtask/PyjUd tag`, ProcessExited(128)) [128]
│ Stacktrace:
│ [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│ [2] pipeline_error at ./process.jl:705 [inlined]
│ [3] (::getfield(Base, Symbol("##500#501")){Base.Process,Base.PipeEndpoint})() at ./process.jl:558
│ [4] iterate(::Base.EachLine{Base.PipeEndpoint}, ::Nothing) at ./io.jl:880 (repeats 2 times)
│ [5] _collect(::UnitRange{Int64}, ::Base.EachLine{Base.PipeEndpoint}, ::Base.HasEltype, ::Base.SizeUnknown) at ./array.jl:568
│ [6] collect at ./array.jl:557 [inlined]
│ [7] #readlines#272 at ./io.jl:414 [inlined]
│ [8] readlines at ./io.jl:414 [inlined]
│ [9] find_prev_tag(::String) at /Users/chentianchi/.julia/packages/Libtask/PyjUd/deps/build.jl:3
│ [10] include_build_script(::SubString{String}, ::Bool) at /Users/chentianchi/.julia/packages/Libtask/PyjUd/deps/build.jl:15
│ [11] top-level scope at none:0
│ [12] include at ./boot.jl:317 [inlined]
│ [13] include_relative(::Module, ::String) at ./loading.jl:1044
│ [14] include(::Module, ::String) at ./sysimg.jl:29
│ [15] include(::String) at ./client.jl:392
│ [16] top-level scope at none:0
│ in expression starting at /Users/chentianchi/.julia/packages/Libtask/PyjUd/deps/build.jl:22
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097

(v1.0) pkg>

[Tianchi Chen - Contact Using Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=pn75be)

On February 19, 2019 at 23:29 GMT, Mohamed Tarek <notifications@github.com> wrote:

Can you post which version of Turing, Libtask and Julia you are using? It may help to do ]up followed by ]build Libtask, then try using Turing.

**Comment by mohamed82008** [comment] 2019-02-19 23:42
Make sure you have internet access when building Libtask.

**Comment by danielchen26** [comment] 2019-02-19 23:43
Yeah, I connect with the school network, pretty fast

-- 
Get the Boomerang Email App <http://boomerangapp.com/mobile> on your phone



----------
On Tue, Feb 19, 2019 at 6:42 PM, Mohamed Tarek <notifications@github.com>
wrote:

Make sure you have internet access when building Libtask.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TuringLang/Turing.jl/issues/690#issuecomment-465357967>,
or mute the thread

**Comment by mohamed82008** [comment] 2019-02-19 23:45
It seems that this line is failing https://github.com/TuringLang/Libtask.jl/blob/master/deps/build.jl#L13. @KDr2 should know better.

**Comment by yebai** [comment] 2019-02-20 08:45
I can't reproduce this error. Perhaps try reinstall `Libtask`? The following works on my laptop with Julia 1.0.3:

```julia
] up Libtask
] build Libtask
```

**Comment by danielchen26** [comment] 2019-02-20 18:08
It seems that build Libtask gives me error:

(v1.0) pkg> build Libtask
Building Libtask → `~/.julia/packages/Libtask/PyjUd/deps/build.log`
┌ Error: Error building `Libtask`:
│ dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
│ Referenced from: /Users/chentianchi/anaconda3/lib/libssh2.1.dylib
│ Reason: image not found
│ fatal: not a git repository (or any of the parent directories): .git
│ ERROR: LoadError: failed process: Process(`git -C /Users/chentianchi/.julia/packages/Libtask/PyjUd tag`, ProcessExited(128)) [128]
│ Stacktrace:
│ [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│ [2] pipeline_error at ./process.jl:705 [inlined]
│ [3] (::getfield(Base, Symbol("##500#501")){Base.Process,Base.PipeEndpoint})() at ./process.jl:558
│ [4] iterate(::Base.EachLine{Base.PipeEndpoint}, ::Nothing) at ./io.jl:880 (repeats 2 times)
│ [5] _collect(::UnitRange{Int64}, ::Base.EachLine{Base.PipeEndpoint}, ::Base.HasEltype, ::Base.SizeUnknown) at ./array.jl:568
│ [6] collect at ./array.jl:557 [inlined]
│ [7] #readlines#272 at ./io.jl:414 [inlined]
│ [8] readlines at ./io.jl:414 [inlined]
│ [9] find_prev_tag(::String) at /Users/chentianchi/.julia/packages/Libtask/PyjUd/deps/build.jl:3
│ [10] include_build_script(::SubString{String}, ::Bool) at /Users/chentianchi/.julia/packages/Libtask/PyjUd/deps/build.jl:15
│ [11] top-level scope at none:0
│ [12] include at ./boot.jl:317 [inlined]
│ [13] include_relative(::Module, ::String) at ./loading.jl:1044
│ [14] include(::Module, ::String) at ./sysimg.jl:29
│ [15] include(::String) at ./client.jl:392
│ [16] top-level scope at none:0
│ in expression starting at /Users/chentianchi/.julia/packages/Libtask/PyjUd/deps/build.jl:22
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097

[Tianchi Chen - Contact Using Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=pn8l2u)

On February 20, 2019 at 8:45 GMT, Hong Ge <notifications@github.com> wrote:

I can't reproduce this error. Perhaps try reinstall Libtask? The following works on my laptop with Julia 1.0.3:
] up Libtask ] build Libtask

**Comment by yebai** [comment] 2019-02-20 20:01
@KDr2 Seems like a Windows issue, could you take a look?

**Comment by mohamed82008** [comment] 2019-02-21 03:35
I tried it on Windows, and I cannot reproduce the error. I think the download line is failing somehow, could be tightened security in the school. @danielchen26 try `]dev Libtask` to download the whole repo. I think when the download fails, the build script tries to query the version of the repo, but `Pkg` doesn't download the whole git repo when you do `]add Libtask`. Also try removing the `try catch` block around the download line, but keep the download, to see the error. Once you call `]dev Libtask`, you can modify the code from `.julia/dev/Libtask/deps/build.jl` and then run `]build Libtask` again.

**Comment by danielchen26** [comment] 2019-02-21 03:47
The build.jl is like the following:

function find_prev_tag(tag)
project_root = (@__DIR__) |> dirname |> abspath
tags = readlines(`git -C $project_root tag`)
sort!(tags)
idx = indexin([tag], tags)[1]
if idx == nothing return "NO-PREV-TAG" end
return get(tags, idx - 1, "NO-PREV-TAG")
end

function include_build_script(version_str, try_prev=false)
build_script_url = "https://github.com/TuringLang/Libtask.jl/releases/download/v$(version_str)/build_LibtaskDylib.v$(version_str).jl"
build_script = joinpath(@__DIR__, "tmp-build.jl")
build_script = try download(build_script_url, build_script) catch end
if build_script == nothing && try_prev # no such file
version_str = find_prev_tag("v$version_str") |> strip |> (x) -> lstrip(x, ['v'])
return include_build_script(version_str, false)
end
include(build_script)
end

version_str = read(joinpath(@__DIR__, "../VERSION"), String) |> strip |> (x) -> lstrip(x, ['v'])
include_build_script(version_str, true)

I did the following just now. it gives me the following:

(v1.0) pkg> dev Libtask
Updating git-repo `https://github.com/TuringLang/Libtask.jl.git`
[ Info: Path `/Users/chentianchi/.julia/dev/Libtask` exists and looks like the correct package, using existing path instead of cloning
Resolving package versions...
Updating `~/.julia/environments/v1.0/Project.toml`
[no changes]
Updating `~/.julia/environments/v1.0/Manifest.toml`
[no changes]

(v1.0) pkg> build Libtask
Building Libtask → `~/.julia/dev/Libtask/deps/build.log`
Resolving package versions...
┌ Error: Error building `Libtask`:
│ dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
│ Referenced from: /Users/chentianchi/anaconda3/lib/libssh2.1.dylib
│ Reason: image not found
│ dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
│ Referenced from: /Users/chentianchi/anaconda3/lib/libssh2.1.dylib
│ Reason: image not found
│ ERROR: LoadError: MethodError: no method matching include(::Nothing)
│ Closest candidates are:
│ include(!Matched::AbstractString) at client.jl:392
│ Stacktrace:
│ [1] include_build_script(::SubString{String}, ::Bool) at /Users/chentianchi/.julia/dev/Libtask/deps/build.jl:18
│ [2] include_build_script(::SubString{String}, ::Bool) at /Users/chentianchi/.julia/dev/Libtask/deps/build.jl:16
│ [3] top-level scope at none:0
│ [4] include at ./boot.jl:317 [inlined]
│ [5] include_relative(::Module, ::String) at ./loading.jl:1044
│ [6] include(::Module, ::String) at ./sysimg.jl:29
│ [7] include(::String) at ./client.jl:392
│ [8] top-level scope at none:0
│ in expression starting at /Users/chentianchi/.julia/dev/Libtask/deps/build.jl:22
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097

[Tianchi Chen - Contact Using Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=pn9bu9)

On February 21, 2019 at 3:35 GMT, Mohamed Tarek <notifications@github.com> wrote:

I tried it on Windows, and I cannot reproduce the error. I think the download line is failing somehow, could be tightened security in the school. [@danielchen26](https://github.com/danielchen26) try ]dev Libtask to download the whole repo. I think when the download fails, the build script tries to query the version of the repo, but Pkg doesn't download the whole git repo when you do ]add Libtask. Also try removing the try catch block around the download line, but keep the download, to see the error. Once you call ]dev Libtask, you can modify the code from .julia/dev/Libtask/deps/build.jl and then run ]build Libtask again.

**Comment by mohamed82008** [comment] 2019-02-21 04:06
Copy and paste this into the build file and re-run `]build Libtask`:
```julia
function find_prev_tag(tag)
    project_root = (@__DIR__) |> dirname |> abspath
    tags = readlines(`git -C $project_root tag`)
    sort!(tags)
    idx = indexin([tag], tags)[1]
    if idx == nothing return "NO-PREV-TAG" end
    return get(tags, idx - 1, "NO-PREV-TAG")
end

function include_build_script(version_str, try_prev=false)
    build_script_url = "https://github.com/TuringLang/Libtask.jl/releases/download/v$(version_str)/build_LibtaskDylib.v$(version_str).jl"
    build_script = joinpath(@__DIR__, "tmp-build.jl")
    build_script = download(build_script_url, build_script)
    if build_script == nothing && try_prev # no such file
        version_str = find_prev_tag("v$version_str") |> strip |> (x) -> lstrip(x, ['v'])
        return include_build_script(version_str, false)
    end
    include(build_script)
end

version_str = read(joinpath(@__DIR__, "../VERSION"), String) |> strip |> (x) -> lstrip(x, ['v'])
include_build_script(version_str, true)
```

Also note that you can do 
\```julia
code
\```
to make your code more readable.

**Comment by danielchen26** [comment] 2019-02-21 04:10
I think it still gives me the same thing.

(v1.0) pkg> build Libtask
Building Libtask → `~/.julia/dev/Libtask/deps/build.log`
Resolving package versions...
┌ Error: Error building `Libtask`:
│ dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
│ Referenced from: /Users/chentianchi/anaconda3/lib/libssh2.1.dylib
│ Reason: image not found
│ ERROR: LoadError: failed process: Process(`curl -g -L -f -o /Users/chentianchi/.julia/dev/Libtask/deps/tmp-build.jl https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/build_LibtaskDylib.v0.2.5.jl`, ProcessSignaled(6)) [0]
│ Stacktrace:
│ [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│ [2] pipeline_error at ./process.jl:705 [inlined]
│ [3] #run#503(::Bool, ::Function, ::Cmd) at ./process.jl:663
│ [4] run at ./process.jl:661 [inlined]
│ [5] download(::String, ::String) at ./download.jl:27
│ [6] include_build_script(::SubString{String}, ::Bool) at /Users/chentianchi/.julia/dev/Libtask/deps/build.jl:38
│ [7] top-level scope at none:0
│ [8] include at ./boot.jl:317 [inlined]
│ [9] include_relative(::Module, ::String) at ./loading.jl:1044
│ [10] include(::Module, ::String) at ./sysimg.jl:29
│ [11] include(::String) at ./client.jl:392
│ [12] top-level scope at none:0
│ in expression starting at /Users/chentianchi/.julia/dev/Libtask/deps/build.jl:47
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097

My build.jl is what you copied me:
```julia
function find_prev_tag(tag)
project_root = (@__DIR__) |> dirname |> abspath
tags = readlines(`git -C $project_root tag`)
sort!(tags)
idx = indexin([tag], tags)[1]
if idx == nothing return "NO-PREV-TAG" end
return get(tags, idx - 1, "NO-PREV-TAG")
end

function include_build_script(version_str, try_prev=false)
build_script_url = "https://github.com/TuringLang/Libtask.jl/releases/download/v$(version_str)/build_LibtaskDylib.v$(version_str).jl"
build_script = joinpath(@__DIR__, "tmp-build.jl")
build_script = download(build_script_url, build_script)
if build_script == nothing && try_prev # no such file
version_str = find_prev_tag("v$version_str") |> strip |> (x) -> lstrip(x, ['v'])
return include_build_script(version_str, false)
end
include(build_script)
end

version_str = read(joinpath(@__DIR__, "../VERSION"), String) |> strip |> (x) -> lstrip(x, ['v'])
include_build_script(version_str, true)
```

[Tianchi Chen - Contact Using Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=pn9cy0)

On February 21, 2019 at 4:06 GMT, Mohamed Tarek <notifications@github.com> wrote:

Copy and paste this into the build file and re-run ]build Libtask:
function find_prev_tag(tag) project_root = (@__DIR__) |> dirname |> abspath tags = readlines(`git -C $project_root tag`) sort!(tags) idx = indexin([tag], tags)[1] if idx == nothing return "NO-PREV-TAG" end return get(tags, idx - 1, "NO-PREV-TAG") end function include_build_script(version_str, try_prev=false) build_script_url = "https://github.com/TuringLang/Libtask.jl/releases/download/v$(version_str)/build_LibtaskDylib.v$(version_str).jl" build_script = joinpath(@__DIR__, "tmp-build.jl") build_script = download(build_script_url, build_script) if build_script == nothing && try_prev # no such file version_str = find_prev_tag("v$version_str") |> strip |> (x) -> lstrip(x, ['v']) return include_build_script(version_str, false) end include(build_script) end version_str = read(joinpath(@__DIR__, "../VERSION"), String) |> strip |> (x) -> lstrip(x, ['v']) include_build_script(version_str, true)

Also note that you can do
```julia
code
```
to make your code more readable.

**Comment by mohamed82008** [comment] 2019-02-21 04:24
So it seems the download is failing. Try
```julia
run(`curl -g -L -f -o /Users/chentianchi/.julia/dev/Libtask/deps/tmp-build.jl https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/build_LibtaskDylib.v0.2.5.jl`)
```
in a Julia REPL, you should get the same error. The file it is trying to download is the first one [here](https://github.com/TuringLang/Libtask.jl/releases/tag/v0.2.5). See if you can download it separately.

**Comment by danielchen26** [comment] 2019-02-21 04:30
Here is what it looks like:
```
shell> curl -g -L -f -o /Users/chentianchi/.julia/dev/Libtask/deps/tmp-build.jl https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/build_LibtaskDylib.v0.2.5.jl
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
Referenced from: /Users/chentianchi/anaconda3/lib/libssh2.1.dylib
Reason: image not found
/bin/bash: line 1: 21027 Abort trap: 6 ( curl -g -L -f -o '/Users/chentianchi/.julia/dev/Libtask/deps/tmp-build.jl' 'https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/build_LibtaskDylib.v0.2.5.jl'; )
```
I have downloaded [build_LibtaskDylib.v0.2.5.jl](https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/build_LibtaskDylib.v0.2.5.jl) separately, should put it in a specific folder?

[Tianchi Chen - Contact Using Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=pn9dve)

On February 21, 2019 at 4:24 GMT, Mohamed Tarek <notifications@github.com> wrote:

So it seems the download is failing. Try
run(`curl -g -L -f -o /Users/chentianchi/.julia/dev/Libtask/deps/tmp-build.jl https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/build_LibtaskDylib.v0.2.5.jl`)

in a Julia REPL, you should get the same error. The file it is trying to download is the first one [here](https://github.com/TuringLang/Libtask.jl/releases/tag/v0.2.5). See if you can download it separately.

**Comment by danielchen26** [comment] 2019-02-21 04:33
```bash
shell> curl -g -L -f -o /Users/chentianchi/.julia/dev/Libtask/deps/tmp-build.jl https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/build_LibtaskDylib.v0.2.5.jl
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/chentianchi/anaconda3/lib/libssh2.1.dylib
  Reason: image not found
/bin/bash: line 1: 21027 Abort trap: 6           ( curl -g -L -f -o '/Users/chentianchi/.julia/dev/Libtask/deps/tmp-build.jl' 'https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/build_LibtaskDylib.v0.2.5.jl' )
```
This is what I got
sorry I used email to reply it does not show the correct markdown format.

**Comment by mohamed82008** [comment] 2019-02-21 04:40
I am still not entirely sure what the exact problem here is and so not sure what a suitable workaround is. Perhaps @yebai or @KDr2 know better. You can try running the downloaded file in the `deps` directory.

**Comment by danielchen26** [comment] 2019-02-21 04:41
ok, Thank you for your help

**Comment by KDr2** [comment] 2019-02-21 13:54
@danielchen26 

Please make sure your `download` function in Julia works well, you can download any file whose URL starts with "https://" to test it. The build process of `Libtask` need to download 2 files from Github using this function: the `build.jl` and then the binaries tarball.

If you have trouble to fix it, there's a workaround:

1. create the file `deps.jl` under the deps directory of the Libtask pkg(some path like ` ~/.julia/packages/Libtask/tarFc`). Below is the file content:

```
if isdefined((@static VERSION < v"0.7.0-DEV.484" ? current_module() : @__MODULE__), :Compat)
    import Compat.Libdl
elseif VERSION >= v"0.7.0-DEV.3382"
    import Libdl
end
const libtask_v1_0 = joinpath(dirname(@__FILE__), "usr/lib/libtask_v1_0.so")
const libtask_v1_1 = joinpath(dirname(@__FILE__), "usr/lib/libtask_v1_1.so")
function check_deps()
end
```

2. download the binaries for you OS, unpack it, place the files(`*.dll/*.so/*.dylib`) in it to `~/.julia/packages/Libtask/tarFc/deps/usr/lib/`

3. Don't build the pkg, just using it.


The directory structure on my linux box:
``` sh
$ ls ~/.julia/packages/Libtask/tarFc/deps/
build_dylib.sh  build.jl  build.log  build_tarballs.jl  deps.jl  Makefile  task.c  tmp-build.jl  usr
$ cat ~/.julia/packages/Libtask/tarFc/deps/deps.jl
if isdefined((@static VERSION < v"0.7.0-DEV.484" ? current_module() : @__MODULE__), :Compat)
    import Compat.Libdl
elseif VERSION >= v"0.7.0-DEV.3382"
    import Libdl
end
const libtask_v1_0 = joinpath(dirname(@__FILE__), "usr/lib/libtask_v1_0.so")
const libtask_v1_1 = joinpath(dirname(@__FILE__), "usr/lib/libtask_v1_1.so")
function check_deps()
    # ...
end
$ ls ~/.julia/packages/Libtask/tarFc/deps/usr/lib/
libtask_v1_0.so  libtask_v1_1.so
```

**Comment by mohamed82008** [comment] 2019-02-24 05:33
@danielchen26 is this still a problem for you?

**Comment by danielchen26** [comment] 2019-02-24 06:16
Sorry for the late reply, I was in an urgent working on something else these days. 
<img width="553" alt="screen shot 2019-02-24 at 1 04 49 am" src="https://user-images.githubusercontent.com/5272189/53295758-3dbc8100-37d0-11e9-91f4-611e939831d8.png">

Under Libtask folder, I have structure like what shows in the picture. I have created a deps.jl which is what you wrote under the folder PyjUd.

The folder PyjUd/deps does not contain the usr/lib. should I create another folder? 
I downloaded the files(1. [LibtaskDylib.v0.2.5.x86_64-apple-darwin14.tar.gz](https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/LibtaskDylib.v0.2.5.x86_64-apple-darwin14.tar.gz)) for macOS. the deps folder contains only two files: libtask_v1_0.dylib, libtask_v1_1.dylib. should I put them into PyjUd/deps/usr/lib?

Also, I think the error somehow related to my local installed anaconda.  The building error shows:
```julia
(v1.0) pkg> build Libtask
  Building Libtask → `~/.julia/dev/Libtask/deps/build.log`
 Resolving package versions...
┌ Error: Error building `Libtask`:
│ dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
│   Referenced from: /Users/chentianchi/anaconda3/lib/libssh2.1.dylib
│   Reason: image not found
│ ERROR: LoadError: failed process: Process(`curl -g -L -f -o /Users/chentianchi/.julia/dev/Libtask/deps/tmp-build.jl https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/build_LibtaskDylib.v0.2.5.jl`, ProcessSignaled(6)) [0]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│  [2] pipeline_error at ./process.jl:705 [inlined]
│  [3] #run#503(::Bool, ::Function, ::Cmd) at ./process.jl:663
│  [4] run at ./process.jl:661 [inlined]
│  [5] download(::String, ::String) at ./download.jl:27
│  [6] include_build_script(::SubString{String}, ::Bool) at /Users/chentianchi/.julia/dev/Libtask/deps/build.jl:38
│  [7] top-level scope at none:0
│  [8] include at ./boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at ./loading.jl:1044
│  [10] include(::Module, ::String) at ./sysimg.jl:29
│  [11] include(::String) at ./client.jl:392
│  [12] top-level scope at none:0
│ in expression starting at /Users/chentianchi/.julia/dev/Libtask/deps/build.jl:47
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097
```
I just tested download function in julia seems working:
```julia
julia> download("https://www-thphys.physics.ox.ac.uk/people/JamesBinney/qb.pdf")

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3289k  100 3289k    0     0   865k      0  0:00:03  0:00:03 --:--:--  865k
"/var/folders/9p/5vk2bsmx0pvg8s079rtjcph40000gn/T/juliavoFDIc"

julia>
```

**Comment by KDr2** [comment] 2019-02-25 01:10
> The folder PyjUd/deps does not contain the usr/lib. should I create another folder?
> I downloaded the files(1. [LibtaskDylib.v0.2.5.x86_64-apple-darwin14.tar.gz](https://github.com/TuringLang/Libtask.jl/releases/download/v0.2.5/LibtaskDylib.v0.2.5.x86_64-apple-darwin14.tar.gz)) for macOS. the deps folder contains only two files: libtask_v1_0.dylib, libtask_v1_1.dylib. should I put them into PyjUd/deps/usr/lib?

Yes, please try these steps:
1. create the dir `PyjUd/deps/usr/lib` and put the `*.dylib` files there.
2. change the content of the file `deps.jl`
3. `using Libtask` in the Julia repl, don't build it.

**Comment by KDr2** [comment] 2019-02-25 01:16
The error stacktrace says it try to run the `curl` command from an anaconda evironment, and libssh2 can not be found in that env. 

Could you paste the output of  `versioninfo(verbose=true)` after the building error and after the successful download call? May be these hava different PATH settings so different `curl` executable are used. 

Thanks.

**Comment by danielchen26** [comment] 2019-02-25 02:44
I think I just sucessfully build the libtask and turing.
It turns out that. I have another folder ```.julia/dev/Libtask``` instead the folder I mentioned ```.julia/packages/Libtask```. I put the deps.jl under the ```.julia/dev/Libtask/deps/deps.jl``` and put lib folder under ```.julia/dev/Libtask``` and then rebuild Libtask. Then everything works.

Thank you for your help!!

**Comment by danielchen26** [comment] 2019-02-25 02:46
I am curious why I have two Libtask at two locations.  Is the one ```.julia/packages/Libtask``` redundant or useless? Julia is using the one under the dev/Libtask. why is that?

**Comment by KDr2** [comment] 2019-02-25 04:29
```
 pkg> ?develop
  develop [--shared|--local] pkg[=uuid] ...

  Make a package available for development. If pkg is an existing local path that path will be recorded in the manifest and used. Otherwise, a full git clone of pkg at rev rev is made. The location of the
  clone is controlled by the --shared (default) and --local arguments. The --shared location defaults to ~/.julia/dev, but can be controlled with the JULIA_PKG_DEVDIR environment variable. When --local is
  given, the clone is placed in a dev folder in the current project. This operation is undone by free.

  Example

  pkg> develop Example
  pkg> develop https://github.com/JuliaLang/Example.jl
  pkg> develop ~/mypackages/Example
  pkg> develop --local Example
```

Maybe you had run `develop Libtask` in the pkg REPL, You can try to run `free Libtask` to free the pkg under the dir `~/.julia/dev`.

**Comment by yebai** [comment] 2019-03-04 21:59
I'm closing this issue now because it seems to be related to `anaconda` instead of `Turing`.

**Closed by yebai** 2019-03-04 21:59 UTC
