### ISSUE TITLE
s^2 notation in docs/src/using-turing/sampler-viz.md

### ISSUE THREAD

**Issue by PeetoomHeida** [TuringLang/Turing.jl#1793] opened 2022-03-10 19:52 UTC
Lines 35, 51, 52 of this file haven't been updated to match the change from s to s^2.

**Comment by rikhuijzer** [comment] 2022-03-10 19:58
This issue isn't scoring points for clarity I'm afraid. I had to do some digging and I'm still not sure what is the problem.

So, the issue is that the changes from https://github.com/TuringLang/Turing.jl/pull/1606 are not visible somewhere?

The webpage looks fine: https://turing.ml/dev/docs/using-turing/sampler-viz

**Comment by PeetoomHeida** [comment] 2022-03-10 20:27
Newish to using git, so sorry for being vauge. iI hink I made a pull request that shows the changes.

**Comment by yebai** [comment] 2022-03-11 08:19
Fixed by #1795

**Closed by yebai** 2022-03-11 08:19 UTC
