### ISSUE TITLE
Numerical Error (Beta regression)

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/Turing.jl#855] opened 2019-07-15 02:29 UTC
I'm getting a numerical error on a Beta regression -- it looks like something's happening with the gradients and causing the parameters to flip to `-Inf`. Anyone have any tips? Do I need a custom gradient function here?

MWE: 

```julia
using Turing
using Statistics
using LinearAlgebra
using DataFrames
using StatFiles
using CSVFiles
using Tracker
using StatsFuns

Turing.setadbackend(:reverse_diff)

@model betareg(Y, X) = begin
    num_x = size(X, 2)
    ϕ = length(Y)

    β = Vector(undef, num_x)
    for i in 1:num_x
        β[i] ~ Normal(mean(X[:,i]))
    end

    for i in eachindex(Y)
        η = dot(X[i,:], β)
        μ = logistic(η)
        Y[i] ~ Beta(μ, ϕ)
    end
end

Y = Union{Missing, Float32}[0.0, 1.0, 1.0, 1.0, 0.0, 1.0]

x1 = Union{Missing, Float32}[380.0, 660.0, 800.0, 640.0, 520.0, 760.0]
x2 = Union{Missing, Float32}[3.61,   3.67,   4.0,  3.19,  2.93,   3.0]
x3 = Union{Missing, Float32}[3.0, 3.0, 1.0, 4.0, 4.0, 2.0]

X = hcat(x1, x2, x3)
func = betareg(Y, X)

chn = sample(func, NUTS(1000, 0.7))
```

Error:

```julia
ERROR: LoadError: ArgumentError: Beta: the condition α > zero(α) && β > zero(β) is not satisfied.
Stacktrace:
 [1] macro expansion at /home/cameron/.julia/packages/Distributions/Iltex/src/utils.jl:6 [inlined]
 [2] Type at /home/cameron/.julia/packages/Distributions/Iltex/src/univariate/continuous/beta.jl:34 [inlined]
 [3] Type at /home/cameron/.julia/packages/Distributions/Iltex/src/univariate/continuous/beta.jl:39 [inlined]
 [4] Beta(::Tracker.TrackedReal{Float64}, ::Int64) at /home/cameron/.julia/packages/Distributions/Iltex/src/univariate/continuous/beta.jl:40
 [5] macro expansion at /home/cameron/.julia/dev/Turing/src/core/compiler.jl:44 [inlined]
 [6] macro expansion at /home/cameron/code/julia/beta-reg/beta-regression.jl:31 [inlined]
 [7] (::getfield(Main, Symbol("###inner_function#1510#353")))(::Turing.Core.RandomVariables.VarInfo{NamedTuple{(:β,),Tuple{Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:β},Int64},Array{Normal{Float64},1},Array{Turing.Core.RandomVariables.VarName{:β},1},TrackedArray{…,Array{Float64,1}},Array{Set{Turing.Selector},1}}}},Tracker.TrackedReal{Float64}}, ::Turing.Sampler{NUTS{Turing.Core.TrackerAD,(),AdvancedHMC.Adaptation.DenseEuclideanMetric}}, ::Turing.Model{Tuple{:β},Tuple{:Y,:X},getfield(Main, Symbol("###inner_function#1510#353")),NamedTuple{(:Y, :X),Tuple{Array{Union{Missing, Float32},1},Array{Float32,2}}},NamedTuple{(:Y, :X),Tuple{Symbol,Symbol}}}) at /home/cameron/.julia/dev/Turing/src/core/compiler.jl:438
 [8] #call#3 at /home/cameron/.julia/dev/Turing/src/Turing.jl:73 [inlined]
 [9] Model at /home/cameron/.julia/dev/Turing/src/Turing.jl:73 [inlined]
 [10] runmodel!(::Turing.Model{Tuple{:β},Tuple{:Y,:X},getfield(Main, Symbol("###inner_function#1510#353")),NamedTuple{(:Y, :X),Tuple{Array{Union{Missing, Float32},1},Array{Float32,2}}},NamedTuple{(:Y, :X),Tuple{Symbol,Symbol}}}, ::Turing.Core.RandomVariables.VarInfo{NamedTuple{(:β,),Tuple{Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:β},Int64},Array{Normal{Float64},1},Array{Turing.Core.RandomVariables.VarName{:β},1},TrackedArray{…,Array{Float64,1}},Array{Set{Turing.Selector},1}}}},Tracker.TrackedReal{Float64}}, ::Turing.Sampler{NUTS{Turing.Core.TrackerAD,(),AdvancedHMC.Adaptation.DenseEuclideanMetric}}) at /home/cameron/.julia/dev/Turing/src/core/RandomVariables.jl:694
```

The last couple draws of the beta parameter:

```julia
Any[0.774515 (tracked), 0.645201 (tracked), 1.66691 (tracked)]
Any[NaN (tracked), NaN (tracked), NaN (tracked)]
```

**Comment by trappmartin** [comment] 2019-07-18 14:12
I had a similar problem with logistic regression. @xukai92 suggested to use a numerical stable version of `BinomialLogit` in my case. But I think this is inconvenient as it requires to implement a custom distribution for each corner case.

Maybe you could instead use a numerical stable version of `logistic`?
Something like this (which I believe is the standard way to achieve this):
```julia
sigmoid(x::T) where {T<:Real} = x >= zero(x) ? inv(exp(-x) + one(x)) : exp(x) / (exp(x) + one(x))
```
@xukai92 do you have a better solution?

**Comment by cpfiffer** [comment] 2019-07-28 00:12
I gave the `sigmoid` function a shot, and I still get `Inf` parameters.

**Comment by xukai92** [comment] 2019-09-07 02:08
I think it's difficult to make things stable in general unless you make things in the logit/log space, e.g. `BinomialLogit` here.

**Comment by xukai92** [comment] 2019-09-07 02:08
We have `BinomialLogit` already - maybe give a try?

**Comment by xukai92** [comment] 2019-09-07 02:09
Opps it seems no.

**Comment by xukai92** [comment] 2019-09-07 02:17
After checking the `logpdf` of Beta (https://github.com/JuliaStats/StatsFuns.jl/blob/master/src/distrs/beta.jl#L19) I guess it's more tricky. It doesn't seem to be related to if alpha and beta are in log or logit space.

In fact, `log1p(-x)` might be problematic if `x` is `1.0` and in your example `Y[i]` could be `1.0` - might this is the issue?

**Comment by xukai92** [comment] 2019-09-07 02:19
Also regarding the error, I think the direct cause is that `μ = logistic(η)` is too close to `0`, maybe just try `μ = logistic(η) + 1e-6`?

**Comment by willtebbutt** [comment] 2019-09-07 07:49
Probably a slightly better choice is something like
```julia
lb, ub = 1e-6, 1 - 1e-6
μ = logistic(η) * (ub - lb) + lb
```
which would constrain `μ` to lie between `lb` and `ub`.

> In fact, log1p(-x) might be problematic if x is 1.0 and in your example Y[i] could be 1.0
Agreed, the logpdf of `Beta` is definitely problematic for `x == 0` and `x == 1`.

**Comment by xukai92** [comment] 2019-09-07 09:59
I believe `μ` is only constrained to be positive?

**Comment by willtebbutt** [comment] 2019-09-07 14:51
> I believe μ is only constrained to be positive?

Right you are. Should've read the code. Just assumed it was between 0 and 1 because `logistic`.

**Comment by yebai** [comment] 2019-10-03 19:33
Is this fixed now?

**Comment by cpfiffer** [comment] 2019-10-03 20:52
For now, yes.

**Closed** 2019-10-03 20:55 UTC
